#!/usr/bin/env bash
# This script is displaying number from 1 to 20 times using while loop
counter=1

while [ $counter -le 20 ];do
      case "$counter" in
	  "5")
	      echo "bad luck from China"
	      ;;
	  "10")
	      echo "bad luck from Japan"
	      ;;
	  "18")
	      echo "bad luck from Italy"
	      ;;
	  *)
	      echo "$counter"
	      ;;
      esac
      ((counter++))
done
